---

Reconecte ao Drive.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
DRIVE_DIRECTORY = "curso_ml"
DRIVE_DIRECTORY = os.path.join("/content/drive/MyDrive", DRIVE_DIRECTORY)

---

In [ ]:
import pickle
import numpy as np

## Combinação de classificadores

Mais uma vez, vamos começar carregando os dados de treino e teste a partir do arquivo `cover_types.pkl`.

In [ ]:
___

Também carregue os classificadores salvos no último exercício.

In [ ]:
tree = pickle.___(open(os.path.join(DRIVE_DIRECTORY, ___), 'rb'))
rf = ___
knn = ___
lr = ___
svm = ___
neural_net = ___

Separe o registro de índice 2 de `X_test` em uma variável `new_instance`, aplicando o método `reshape` para que o array resultante seja representado em `1` linha e o número de colunas igual ao número de atributos (você pode usar `-1` para o NumPy determinar este número sozinho). Exiba `new_instance` e seu `shape`.

In [ ]:
new_instance = ___[___].reshape(___, ___)
___, ___.___

(array([[-2.42751612, -0.35810696,  2.39062347, -0.83105729,  0.0410722 ,
         -1.2884323 ,  1.55697188, -1.6248467 , -2.70414875, -0.11760965,
          0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ]]),
 (1, 53))

Agora utilize `new_instance` para obter predições dos algoritmos carregados.

In [ ]:
y_pred_tree = ___
y_pred_rf = ___
y_pred_knn = ___
y_pred_lr = ___
y_pred_svm = ___
y_pred_nn = ___

Exiba os resultados da predições.

In [ ]:
___

(1, 1, 1, 5, 5, 1)

Como este é um problema com mais de uma classe, a lógica para determinar a classe vencedora é um pouco diferente. Vamos começar colocando os resultados em uma lista.

In [ ]:
results = [y_pred_tree[0], ___, ___, ___, ___, ___]

Agora, utilizando a função `np.unique`, vamos determinar quais são as classes preditas e quantas vezes elas foram preditas.

In [ ]:
unique, counts = np.un___(___, re___=___)
unique, counts

(array([1, 5]), array([4, 2]))

Agora é preciso verificar qual a classe que apareceu mais vezes. Primeiro vamos determinar qual a contagem máxima.

In [ ]:
max_counts = counts.max()
max_counts

4

E agora nós conseguimos filtrar as classes que mais apareceram como sendo aquelas cuja contagem é igual á contagem máxima.

In [ ]:
top_classes = unique[counts == max_counts]
top_classes

array([1])

Finalmente, a lógica vai utilizar `top_classes` para exibir os resultados.

In [ ]:
if ___ == ___:
    print("Classe encontrada:", ___)
else:
    print("Empate entre as classes:", ___)

Classe encontrada: 1


## Rejeição de classificadores

Utilize o método `predict_proba` para determinar as probabilidades encontradas pelos classificadores. Entretanto, você precisa deixar o algoritmo SVM de fora, porque da forma que nós o implementamos, ele não retorna valores de probabilidade.

In [ ]:
y_prob_tree = ___
y_prob_rf = ___
y_prob_knn = ___
y_prob_lr = ___
y_prob_nn = ___

y_prob_tree, y_prob_rf, y_prob_knn, y_prob_lr, y_prob_nn

(array([[0., 1., 0., 0., 0., 0., 0.]]),
 array([[0.  , 0.82, 0.01, 0.  , 0.  , 0.17, 0.  ]]),
 array([[0.        , 0.66666667, 0.        , 0.        , 0.        ,
         0.33333333, 0.        ]]),
 array([[2.47802481e-04, 4.33526507e-01, 3.01265019e-02, 6.11261606e-11,
         5.11452977e-03, 5.30974816e-01, 9.84277986e-06]]),
 array([[3.21512033e-08, 7.85099112e-01, 6.12156498e-02, 7.41060801e-19,
         1.04640324e-03, 1.52638797e-01, 5.84329343e-09]]))

Determine a confiança dos classificadores, sendo igual à probabilidade máxima atribuída.

In [ ]:
confidence_tree = ___.max()
confidence_rf = ___
confidence_knn = ___
confidence_lr = ___
confidence_nn = ___

confidence_tree, confidence_rf, confidence_knn, confidence_lr, confidence_nn

(1.0, 0.82, 0.6666666666666666, 0.5309748156237648, 0.7850991118431906)

A lógica em si é parecida com a do problema binário, mas primeiro nós filtramos para manter somente os resultados maiores que a confiança mínima. Depois, aplicamos o mesmo código mostrado na combinação de classificadores.

Utilize uma confiança mínima um pouco mais baixa, já que os resultados encontrados acima são menores. Isso é comum em problemas de classificação com mais de duas classes.

In [ ]:
min_confidence = 0.75
n_algorithms = 0
results = []

if confidence_tree >= min_confidence:
    n_algorithms += 1
    results.append(y_pred_tree[0])

if ___:
    ___
    ___

___

___

___

___, ___ = np.un___(___, ___)
max_counts = ___
top_classes = ___

if ___:
    print(f"Classe encontrada: {___}, baseado em {___} algoritmos.")
else:
    print(f"Empate entre as classes: {___}, baseado em {___} algoritmos.")

Classe encontrada: 1, baseado em 3 algoritmos.
